FROM ubuntu:22.04

RUN apt-get update && apt-get install avahi-utils -y

# set the kernel to use
FROM python:3.10.9-slim
# copy the requirements file
COPY totalInstantPower/requirements.txt requirements.txt
ADD /microserviceBase /microserviceBase
# install the needed requirements
RUN pip3 install -r requirements.txt
RUN pip3 install -r /microserviceBase/requirements.txt

ENV IN_DOCKER Yes
ENV DOCKER_IP "172.20.0.12"

# copy the all the file in the container
COPY /totalInstantPower .
# the command that will be executed when the container will start
CMD ["python3", "-u", "totalInstantPower.py"]