
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#MQTT devices
mqtt:
  switch:
    - unique_id : test_switch
      name : Test Switch
      state_topic : "/home/ts"
      command_topic : "/home/ts/set"
      #"availability_topic" : "home/bedroom/bedroom_socket_switch/available",
      payload_on : "ON"
      payload_off : "OFF"
      state_on : "ON"
      state_off : "OFF"
      optimistic : false
      qos : 0
      retain : true

    - unique_id : test_switch2
      name : Test Switch 2
      state_topic : "/home/ts"
      command_topic : "/home/ts/2/set"
      #"availability_topic" : "home/bedroom/bedroom_socket_switch/available",
      payload_on : "ON"
      payload_off : "OFF"
      state_on : "ON"
      state_off : "OFF"
      optimistic : false
      qos : 0
      retain : true

    - unique_id : test_switch3
      name : Test Switch 3
      state_topic : "/home/ts"
      command_topic : "/home/ts/3/set"
      #"availability_topic" : "home/bedroom/bedroom_socket_switch/available",
      payload_on : "ON"
      payload_off : "OFF"
      state_on : "ON"
      state_off : "OFF"
      optimistic : false
      qos : 0
      retain : true

  sensor:
    - unique_id: test_voltage_sensor
      name: Test Voltage Sensor
      state_topic: "/home/tsens/state"
      device_class: voltage
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltage }}"

    - unique_id: test_current_sensor
      name: Test Current Sensor
      state_topic: "/home/tsens/state"
      device_class: current
      unit_of_measurement: "A"
      value_template: "{{ value_json.current }}"

    - unique_id: test_power_sensor
      name: Test Power Sensor
      state_topic: "/home/tsens/state"
      device_class: power
      unit_of_measurement: "W"
      value_template: "{{ value_json.power }}"

        - unique_id: test_powerh_sensor
      name: Test PowerH Sensor
      state_topic: "/home/tsens/state"
      device_class: energy
      unit_of_measurement: "kWh"
      value_template: "{{ value_json.powerh }}"

  #availability:
      #  - topic: "home/sensor1/status"
      #payload_available: "online"
      #payload_not_available: "offline"
      #json_attributes_topic: "home/tsens/attr"