sensor:
  - unique_id: test_voltage_sensor
    name: Test Voltage Sensor
    state_topic: "/home/tsens/state"
    unit_of_measurement: "V"
    value_template: "{{ value_json.voltage }}"
  
  - unique_id: test_current_sensor
    name: Test Current Sensor
    state_topic: "/home/tsens/state"
    unit_of_measurement: "A"
    value_template: "{{ value_json.current }}"

  - unique_id: test_power_sensor
    name: Test Power Sensor
    state_topic: "/home/tsens/state"
    unit_of_measurement: "W"
    value_template: "{{ value_json.power }}"

  - unique_id: test_powerh_sensor
    name: Test PowerH Sensor
    state_topic: "/home/tsens/state"
    device_class: energy
    unit_of_measurement: "kWh"
    value_template: "{{ value_json.powerh }}"
